<?php
require_once __DIR__ . '/../includes/bootstrap.php'; $user=require_login('seeker'); $pdo=database();
if ($_SERVER['REQUEST_METHOD']==='POST') { verify_csrf(); $action=posted('action');
    if ($action==='profile') {$pdo->prepare('UPDATE job_seekers SET full_name=?,phone=?,address=?,date_of_birth=?,profile_summary=? WHERE user_id=?')->execute([posted('full_name'),posted('phone')?:null,posted('address')?:null,posted('date_of_birth')?:null,posted('profile_summary')?:null,$user['id']]); flash('success','Profile updated.');}
    if ($action==='skill' && posted('skill_name')!=='') {$pdo->prepare('INSERT INTO job_seeker_skills(seeker_id,skill_name,skill_level) VALUES(?,?,?) ON DUPLICATE KEY UPDATE skill_level=VALUES(skill_level)')->execute([$user['id'],posted('skill_name'),posted('skill_level')]); flash('success','Skill saved.');}
    if ($action==='education' && posted('institution')!=='' && posted('degree')!=='') {$pdo->prepare('INSERT INTO education(seeker_id,institution,degree,field_of_study,start_date,end_date,result_gpa) VALUES(?,?,?,?,?,?,?)')->execute([$user['id'],posted('institution'),posted('degree'),posted('field')?:null,posted('start_date')?:null,posted('end_date')?:null,posted('result')?:null]); flash('success','Education added.');}
    if ($action==='experience' && posted('company')!=='' && posted('position')!=='') {$pdo->prepare('INSERT INTO experience(seeker_id,company,position_title,description,start_date,end_date) VALUES(?,?,?,?,?,?)')->execute([$user['id'],posted('company'),posted('position'),posted('description')?:null,posted('start_date'),posted('end_date')?:null]); flash('success','Experience added.');}
    if ($action==='project' && posted('title')!=='') {$pdo->prepare('INSERT INTO projects(seeker_id,title,description,technologies,project_url) VALUES(?,?,?,?,?)')->execute([$user['id'],posted('title'),posted('description')?:null,posted('technologies')?:null,posted('url')?:null]); flash('success','Project added.');}
    if ($action==='certification' && posted('certification_name')!=='') {$pdo->prepare('INSERT INTO certifications(seeker_id,certification_name,issuing_organization,issue_date,credential_url) VALUES(?,?,?,?,?)')->execute([$user['id'],posted('certification_name'),posted('issuer'),posted('issue_date')?:null,posted('url')?:null]); flash('success','Certification added.');}
    if ($action==='language' && posted('language_name')!=='') {$pdo->prepare('INSERT INTO languages(seeker_id,language_name,proficiency) VALUES(?,?,?) ON DUPLICATE KEY UPDATE proficiency=VALUES(proficiency)')->execute([$user['id'],posted('language_name'),posted('proficiency')]); flash('success','Language saved.');} redirect('profile.php'); }
$s=$pdo->prepare('SELECT js.*,u.email FROM job_seekers js JOIN users u ON u.id=js.user_id WHERE js.user_id=?');$s->execute([$user['id']]);$profile=$s->fetch(); page_header('My profile'); ?>
<h1>Profile and CV builder</h1><p><a class="button" href="cv-preview.php">Preview / print CV</a></p><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?=csrf_token() ?>"><input type="hidden" name="action" value="profile"><div><label>Full name</label><input name="full_name" value="<?=e($profile['full_name'])?>" required></div><div><label>Email</label><input value="<?=e($profile['email'])?>" disabled></div><div><label>Phone</label><input name="phone" value="<?=e($profile['phone'])?>"></div><div><label>Date of birth</label><input type="date" name="date_of_birth" value="<?=e($profile['date_of_birth'])?>"></div><div class="full"><label>Address</label><input name="address" value="<?=e($profile['address'])?>"></div><div class="full"><label>Professional summary</label><textarea name="profile_summary"><?=e($profile['profile_summary'])?></textarea></div><div class="full"><button>Save profile</button></div></form>
<section class="grid"><form method="post"><input type="hidden" name="csrf_token" value="<?=csrf_token() ?>"><input type="hidden" name="action" value="skill"><h2>Skill</h2><label>Skill name</label><input name="skill_name" required><label>Level</label><select name="skill_level"><option>beginner</option><option>intermediate</option><option>advanced</option><option>expert</option></select><p><button>Add skill</button></p></form><form method="post"><input type="hidden" name="csrf_token" value="<?=csrf_token() ?>"><input type="hidden" name="action" value="education"><h2>Education</h2><label>Institution</label><input name="institution" required><label>Degree</label><input name="degree" required><label>Field</label><input name="field"><label>Start / end</label><input type="date" name="start_date"><input type="date" name="end_date"><label>Result / GPA</label><input name="result"><p><button>Add education</button></p></form><form method="post"><input type="hidden" name="csrf_token" value="<?=csrf_token() ?>"><input type="hidden" name="action" value="experience"><h2>Experience</h2><label>Company</label><input name="company" required><label>Position</label><input name="position" required><label>Description</label><textarea name="description"></textarea><label>Start date</label><input type="date" name="start_date" required><label>End date</label><input type="date" name="end_date"><p><button>Add experience</button></p></form><form method="post"><input type="hidden" name="csrf_token" value="<?=csrf_token() ?>"><input type="hidden" name="action" value="project"><h2>Project</h2><label>Title</label><input name="title" required><label>Description</label><textarea name="description"></textarea><label>Technologies</label><input name="technologies"><label>URL</label><input name="url" type="url"><p><button>Add project</button></p></form><form method="post"><input type="hidden" name="csrf_token" value="<?=csrf_token() ?>"><input type="hidden" name="action" value="certification"><h2>Certification</h2><label>Name</label><input name="certification_name" required><label>Issuer</label><input name="issuer" required><label>Issue date</label><input type="date" name="issue_date"><label>Credential URL</label><input name="url" type="url"><p><button>Add certification</button></p></form><form method="post"><input type="hidden" name="csrf_token" value="<?=csrf_token() ?>"><input type="hidden" name="action" value="language"><h2>Language</h2><label>Language</label><input name="language_name" required><label>Proficiency</label><select name="proficiency"><option>basic</option><option>conversational</option><option>professional</option><option>native</option></select><p><button>Add language</button></p></form></section>
<?php page_footer(); ?>